### ISSUE TITLE
Dependencies and setup

### ISSUE THREAD

**Issue by bmahoney94** [SeanDaBlack/AbBOT#1]
Having an issue getting this to run.  Any chance you could edit the README.md with instructions and dependencies?  I'm curious enough to want to play with it.

**Comment by ramblingjordan** [comment]
If you have pip installed you should just be able to 'pip instal module_name' for anything it says it can't find. I think selenium and requests for sure. Maybe more.

You also need chrome installed.

Then just run 'py req.py' in a terminal!

Let me know if you have other questions.

**Comment by elementalcollision** [comment]
I've added the modules and have run req.py but am getting "failed" in the output window.  I do see where an instance of Chrome is being controlled but I'm unsure if it's actually passing the data it needs to.  ideas?

**Comment by elementalcollision** [comment]
<img width="767" alt="req py" src="https://user-images.githubusercontent.com/59447757/131903440-91889264-2aed-4245-b499-e5ed1e5587d3.png">
here's the current state d'affairs

**Comment by jensyfrenzy** [comment]
This might be due to the form elements not being rendered on the page.  I'm running into the same issue and the site is _extremely_ slow right now (I can't even get the form to load).

**Comment by ChrisBremseth** [comment]
The form loads in a separate GET request than the page HTML, so I'd bet the script is running before the elements are rendered on the page. Might want to add a check to make sure the form exists before the script runs.

**Comment by elementalcollision** [comment]
> > I've added the modules and have run req.py but am getting "failed" in the output window. I do see where an instance of Chrome is being controlled but I'm unsure if it's actually passing the data it needs to. ideas?
> 
> This might be due to the form elements not being rendered on the page. I'm running into the same issue and the site is _extremely_ slow right now (I can't even get the form to load).

fair play.  I did this a bit earlier in the day where it seemed to be working.  The iOS shortcut worked semi-regularly.

> The form loads in a separate GET request than the page HTML, so I'd bet the script is running before the elements are rendered on the page. Might want to add a check to make sure the form exists before the script runs.

good idea.

**Comment by EnduringBeta** [comment]
Just wanna hop in to say that I too am getting an unaddressed error when I follow the instructions. I newly installed Python 3.9, added it to the path, and in my Git Bash session edited the PATH to include the repo directory with `chromedriver.exe` in it, and on running the program I get:

`OSError: [WinError 193] %1 is not a valid Win32 application`

Lots of people online have experienced this with various answers that don't feel super applicable. Is this about 32/64 bit?

**Comment by elementalcollision** [comment]
Make sure you’re using the correct chromedriver version based on your release.
I run everything through the IDLE interface (versus directly from the command line) and it seems to work with no issues.

 

We should probably tidy up the README for instructions for windows as well.

**Comment by andria-dev** [comment]
This is likely solved, let me know if there's anything unclear in the README about the steps.

**Comment by ramblingjordan** [comment]
Closing as per @andria-dev 's note.
