### ISSUE TITLE
Python issues

### ISSUE THREAD

**Issue by judge2005** [SeanDaBlack/AbBOT#10]
I haven't set up my development environment on this Mac, so I was starting from scratch. First it has python 3 installed, so I have to use pip3. Then I don't have access to the python system library directories, so I have to specify the --user argument to pip3. Then the binary directory isn't on the PATH and the library directory isn't on the PYTHON path, so I fixed those up. But now I'm stumped with this - I'm not a python developer:

```
python req.py 
Traceback (most recent call last):
  File "req.py", line 2, in <module>
    import requests
  File "/Users/Nemesis/Library/Python/3.8/lib/python/site-packages/requests/__init__.py", line 48, in <module>
    from charset_normalizer import __version__ as charset_normalizer_version
  File "/Users/Nemesis/Library/Python/3.8/lib/python/site-packages/charset_normalizer/__init__.py", line 11
SyntaxError: Non-ASCII character '\xd1' in file /Users/Nemesis/Library/Python/3.8/lib/python/site-packages/charset_normalizer/__init__.py on line 12, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by birdaw** [comment]
try:
`python3 req.py`
I got similar errors until adding the 3.

**Comment by judge2005** [comment]
That works. Thanks!

**Comment by elementalcollision** [comment]
We good to close?

**Comment by judge2005** [comment]
Sure
