### ISSUE TITLE
Free software license

### ISSUE THREAD

**Issue by nfitzen** [SeanDaBlack/AbBOT#24]
Would it be possible to add a [free software] license to this code, such as Expat/[`MIT`], [`Apache-2.0`], or [`GPL-3.0-or-later`]?
(See also [the GNU Project's license recs][1] and [FSFE'S REUSE guidelines][2].)

Also, all significant contributors (what that means will be up to your lawyer) will need to approve these changes, because copyright law.

(Obligatory "<span title="I am not a lawyer">IANAL</span>, this is not legal advice" statement here. I just think it's mildly ironic that this tool isn't free.)

[1]: https://www.gnu.org/licenses/license-recommendations.html
[2]: https://reuse.software/

[`MIT`]: https://spdx.org/licenses/MIT.html "Expat/MIT License"
[`Apache-2.0`]: https://spdx.org/licenses/Apache-2.0.html "Apache License 2.0"
[`GPL-3.0-or-later`]: https://spdx.org/licenses/GPL-3.0-or-later.html "GNU General Public License v3.0 or later"

[free software]: https://www.gnu.org/philosophy/free-sw.html "Free as in freedom, not price"

**Comment by ramblingjordan** [comment]
@SeanDaBlack thoughts?

**Comment by ramblingjordan** [comment]
Current contributors:

@SeanDaBlack 
@andria-dev 
@steph-query 
@ChrisBremseth 
@ramblingjordan 
@erikedlund 

I for one would very much support an open source license.

**Comment by SeanDaBlack** [comment]
I fully agree

**Comment by steph-query** [comment]
100%

**Comment by ChrisBremseth** [comment]
Let's do it.

**Comment by erikedlund** [comment]
Agreed

**Comment by ramblingjordan** [comment]
I think we have a quorum on this. @jacobmovingfwd is the only one not to reply so far, but his contribution is a (very helpful) data set, but not any logic.

I'll look into setting this up!

**Comment by ramblingjordan** [comment]
![image](https://user-images.githubusercontent.com/490218/132054568-e87f47cd-84db-463b-b4d3-92f829863d60.png)

Any preferences on license? I've used Apache, GNU 3.0, and MIT in a few different cases. Couldn't tell you the differences off the top of my head.

**Comment by jacobmovingfwd** [comment]
I like Creative Commons, but just from an aesthetic pov, I don't know about the legal differences at all.

**Comment by nfitzen** [comment]
@jacobmovingfwd [Creative Commons shouldn't be used for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

> Any preferences on license? I've used Apache, GNU 3.0, and MIT in a few different cases. Couldn't tell you the differences off the top of my head.

@ramblingjordan [`GPL-3.0-or-later`] is good unless there might be an issue of nonfree dependencies, or if the program is too short to warrant it. Expat/[`MIT`] is a simple all-permissive license that has a warranty disclaimer and a copyright notice. [`Apache-2.0`] most notably includes a patent grant.

[`MIT`]: https://spdx.org/licenses/MIT.html "Expat/MIT License"
[`Apache-2.0`]: https://spdx.org/licenses/Apache-2.0.html "Apache License 2.0"
[`GPL-3.0-or-later`]: https://spdx.org/licenses/GPL-3.0-or-later.html "GNU General Public License v3.0 or later"

**Comment by ramblingjordan** [comment]
Sounds like MIT might be the best option, lets us use any dependencies we might need if I understand that correctly?

Any objections? (Will give some time to let people reply)

**Comment by FOSSilizedDaemon** [comment]
> Sounds like MIT might be the best option, lets us use any dependencies we might need if I understand that correctly?
> 
> Any objections? (Will give some time to let people reply)

The LGPL will let you use non-free dependencies! That way your code can still remain free.

**Comment by nfitzen** [comment]
> The LGPL will let you use non-free dependencies! That way your code can still remain free.

@FOSSilizedDaemon not true. The LGPL allows the code _to be used_ as a nonfree dependency.

Either way, the code is simple enough that Expat is a perfectly fine choice.

**Comment by nfitzen** [comment]
> Any objections? (Will give some time to let people reply)

@ramblingjordan By the way - I wouldn't accept more contributions until this gets sorted. Copyright licensing is an opt-in system, and each new contributor has to explicitly agree until you specify a license in the repo (and then GitHub's ToS does the rest of the work).

I'm going to make a PR if everyone's decided on Expat/[`MIT`] that indicates licenses according to the [REUSE guidelines](https://reuse.software/). That way, it can be as simple as assigning the PR to every contributor.

**Comment by ramblingjordan** [comment]
Good call. Can you hold off just for a bit. We're going to move the repository to my account so we can manage things better and give @SeanDaBlack a break from the monster he's unleashed.

**Comment by LakesideMiners** [comment]
fyi i have reported that user to github for abuse. since, this shit is just insane.

**Comment by nfitzen** [comment]
@LakesideMiners wait, are you talking about me? Yeah, I've posted a lot of issues about free software licensing, because uh- there's a lot of software I'd like to use that isn't free, and I'd like it to be free, so I just ask. I usually follow a set format because it's short and to the point: can you add a free software license, here are 3 good licenses you can use, and here are some more resources.

**Comment by FOSSilizedDaemon** [comment]
> > The LGPL will let you use non-free dependencies! That way your code can still remain free.
> 
> @FOSSilizedDaemon not true. The LGPL allows the code _to be used_ as a dependency to nonfree code. We're considering the opposite; namely, that this code accidentally linked against a nonfree library.
> 
> Either way, the code is simple enough (< 300 lines) that Expat is a perfectly fine choice.

Ahhh my bad, I am still learning about liscening myself so I will stay tuned to this thread in hopes of learning more.

**Comment by ramblingjordan** [comment]
We split the work into multiple repos all with licenses. Thanks!
