### ISSUE TITLE
Moving beyond this one form

### ISSUE THREAD

**Issue by ChrisBremseth** [SeanDaBlack/AbBOT#41]
With the potential of the site being rehosted/changed and other similar sites popping up, should we start focusing on ways to make this project more extensible?

**Comment by LakesideMiners** [comment]
https://www.theverge.com/2021/9/3/22656196/godaddy-texas-right-for-life-abortion-whistleblowing-site
well, its not a potential anymore, it IS going to be re-hosted somewhere else if it dosnt just go away
(this still is great news tho)

**Comment by ramblingjordan** [comment]
We have moved active development to these repos:

- Python Bot - https://github.com/ramblingjordan/AbBOT-python
- iOS Shortcut - https://github.com/ramblingjordan/AbBOT-iOS-shortcut
- Chrome Extension - https://github.com/ramblingjordan/AbBOT-chrome-extension
- Android App - https://github.com/ramblingjordan/AbBOT-android
- Web Site - https://github.com/ramblingjordan/AbBOT-frontend
- API - https://github.com/ramblingjordan/AbBOT-api

Could you recreate this in one of those? I think maybe the AbBOT-python one is best for now as it will likely get the most eyes on it.

Thanks!
