### ISSUE TITLE
Better "data" generation?

### ISSUE THREAD

**Issue by santaanna2021** [SeanDaBlack/AbBOT#43]
List of a few hundred actual OBGYN first names from the Texas Medical Association (alphabetical order, duplicates removed)
[fns.csv](https://github.com/SeanDaBlack/AbBOT/files/7108615/fns.csv)

List of a few hundred actual OBGYN last names from the Texas Medical Association (alphabetical order, duplicates removed)
[lns.csv](https://github.com/SeanDaBlack/AbBOT/files/7108616/lns.csv)

List of all non PO Box zip codes, city names, and counties in Texas
[TX_Zips.csv](https://github.com/SeanDaBlack/AbBOT/files/7108619/TX_Zips.csv)

## Python script for generating "doctor names"
```
with open('fns.csv') as fns:
	reader2 = csv.reader(fns)
	chosen_first=random.choice(list(fns))

with open('lns.csv') as lns:
	reader3=csv.reader(lns)
	chosen_last=random.choice(list(lns))

nameFormat = ['FL','DL','L,F','L', 'DLF']
nF = random.choice(nameFormat)

if nF == 'FL':
	dr = " ".join([chosen_first,chosen_last])
elif nF == 'DL':
	dr = " ".join(["Dr.",chosen_last])
elif nF == 'L,F':
	dr = ", ".join([chosen_last,chosen_first])
elif nF == 'L':
	dr = chosen_last
elif nf == 'DLF':
	dr = " ".join(["Dr.",chosen_first,chosen_last])
```

## Python script for picking geographic location
```
with open('TX_Zips.csv') as zf:
	reader = csv.reader(zf)
	chosen_row=random.choice(list(reader))

stateNames = ['TX','Texas','TEXAS','texas','tx','Tx']
st = random.choice(stateNames)
```

**Comment by ramblingjordan** [comment]
This is great!

We have moved active development of the python bot to this repo: https://github.com/ramblingjordan/AbBOT-python

Could you recreate this issue, or better yet a pull request on that repo?

Thanks!
