### ISSUE TITLE
Telltale Signs of Output from GPT2 (Double Quotes in Particular)

### ISSUE THREAD

**Issue by TheLandfill** [SeanDaBlack/AbBOT#46]
I want to note that GPT2 output, while decent, usually has a ton of telltale signs:

1. The frequent use of double quotes, as if it's quoting from an interview. Almost every paragraph uses double quotes at least once, especially at the end of the first paragraph.
1. Long quotations inside a sentence. Removing these requires more advanced filtering, but something along the lines of removing any sentence with a quote and the word "said."
2. The use of advertisement text. Because of how GPT-2 was trained, it sometimes has words like "Advertisement" on its own line.
1.  Any use of colons for things like quotations in interviews.
2. Characters that are not found on a standard keyboard.
4. Stuff like "All photos © Michael C. Stough" on its own line.
5. While you remove the stuff that comes after the final period, you don't remove any trailing newlines afterwards.

We should try to remove as many of these signs as possible from the output of GPT2. Some of these are easier to remove than others, but the ones that are difficult for us to remove are also difficult for them to filter out. For example, they could remove most of GPT2's submissions by removing any submission with double quotes.

It might also be a good idea to leave these signs in the output every so often so that they implement filters that could remove false negatives. For example, if they implement a filter for quotation marks, they could remove some real submissions that have quotation marks.

**Comment by ChrisBremseth** [comment]
We could use regex to filter all that stuff out as long as we have a list of what to look for.

**Comment by LakesideMiners** [comment]
im somewhat decent with regex, if help is needed im available.

**Comment by rootwork** [comment]
Relatedly, while injecting the names of state Republicans is clever, it also makes for a pretty easy way to filter out submissions coming from this form. I think sticking with the random names (and maybe increasing the number of them) would result in harder-to-filter noise.

**Comment by TheLandfill** [comment]
I would say that filtering out quotation marks should be the last step in general since you can use them as hints for other regular expressions, like long quotes in a sentence.

@ChrisBremseth The best way to generate such a list is to generate a bunch of responses from GPT2 and manually look for patterns, which is how I generated my list.

**Comment by ramblingjordan** [comment]
We have moved active development to these repos:

- Python Bot - https://github.com/ramblingjordan/AbBOT-python
- iOS Shortcut - https://github.com/ramblingjordan/AbBOT-iOS-shortcut
- Chrome Extension - https://github.com/ramblingjordan/AbBOT-chrome-extension
- Android App - https://github.com/ramblingjordan/AbBOT-android
- Web Site - https://github.com/ramblingjordan/AbBOT-frontend
- API - https://github.com/ramblingjordan/AbBOT-api

Could you recreate this issue in the appropriate new repo? I think AbBOT-python is the best bet.

Thanks!
