### ISSUE TITLE
x86_64 Binary for Linux?

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [SeanDaBlack/AbBOT#6]
I keep getting an error:
```
OSError: [Errno 8] Exec format error: './chromedriver'
```
when I attempt to run this script. I did some searching as I also got an error when I did
```
./chromdriver
```
from my shell and got a shell equivalent error and it seems this might be caused by the binary not being for x86_64 systems, is this binary only for ARM? If so can you generate an X86_64 binary or provide the steps to do so?

Thank you for your awesome work!

**Comment by ChrisBremseth** [comment]
It looks like this would give you what you need for ChromeDriver and Selenium: https://gist.github.com/ziadoz/3e8ab7e944d02fe872c3454d17af31a5

**Comment by andria-dev** [comment]
For me, I fixed this by getting the [Chrome Linux selenium driver](https://sites.google.com/a/chromium.org/chromedriver/downloads) and installing the `google-chrome-stable` package.

```bash
wget --content-disposition https://chromedriver.storage.googleapis.com/93.0.4577.15/chromedriver_linux64.zip
unzip chromedriver_linux64.zip
sudo apt install google-chrome-stable
```

**Comment by FOSSilizedDaemon** [comment]
> For me, I fixed this by getting the [Chrome Linux selenium driver](https://sites.google.com/a/chromium.org/chromedriver/downloads) and installing the `google-chrome-stable` package.
> 
> ```shell
> wget --content-disposition https://chromedriver.storage.googleapis.com/93.0.4577.15/chromedriver_linux64.zip
> unzip chromedriver_linux64.zip
> sudo apt install google-chrome-stable
> ```

Let me test this super quick, thank you!

**Comment by FOSSilizedDaemon** [comment]
@andria-dev While the install worked the script just says failed over and over again sadly.

**Comment by andria-dev** [comment]
The site is intermittently down and the script probably won't work until we can figure out a way to either bypass reCaptcha or just display the reCaptcha checkbox and wait for it to be clicked/solved every time.

**Comment by andria-dev** [comment]
We're good to close this now.

**Comment by ramblingjordan** [comment]
Closing as per @andria-dev 's note.
